# Generated by Django 5.0.1 on 2024-02-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_user_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=100),
        ),
    ]
