# Generated by Django 5.0.1 on 2024-02-04 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_user_profile_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='age',
        ),
    ]
