# Generated by Django 5.0.1 on 2024-02-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0007_user_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='age',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
